# Generated by Django 4.2.1 on 2023-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='groups',
            field=models.ManyToManyField(related_name='customer_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='customer_users', to='auth.permission'),
        ),
    ]
