# Generated by Django 4.2.1 on 2023-05-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_customeruser_groups_alter_customeruser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='photo',
            field=models.ImageField(blank=True, default='imgs/alisher.jpg', null=True, upload_to='user_photos'),
        ),
    ]
