# Generated by Django 4.2.1 on 2023-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.ImageField(upload_to='users/img/')),
                ('address', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
