# Generated by Django 4.2.1 on 2023-05-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_users_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
    ]
