# Generated by Django 4.2.1 on 2023-05-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_rename_name_users_username_remove_users_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='name',
        ),
    ]
