# Generated by Django 4.2.1 on 2023-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_rename_username_users_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
