# Generated by Django 4.2 on 2023-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_savedrecipe_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='publication_date',
            field=models.CharField(default='2023-05-29', max_length=10),
            preserve_default=False,
        ),
    ]
