# Generated by Django 4.2.1 on 2023-05-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_rename_name_users_first_name_users_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
