# Generated by Django 4.2.1 on 2023-05-24 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0011_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='ProfileUser',
        ),
    ]
